#!/usr/bin/env bash
# Bash script that will display information about subdomains. 
information ()
{
	domain="$1"
	subdomain="$2"

dig "$subdomain.$domain" | awk '/;; ANSWER SECTION:/{getline; print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}
#ar = ("www" "lb-01" "web-01" "web-02")
for subdomain in "www" "lb-01" "web-01" "web-02" 
do
	if [ -z "$2" ] || [ "$2" == "$subdomain" ];
	then
		information "$1" "$subdomain"
	fi
done
