#!/usr/bin/env bash
# Configure the Nginx server so that to redirect to another page.
# The redirection must be a “301 Moved Permanently”

apt-get -y update && apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

redirect="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "24i $redirect" /etc/nginx/sites-available/default

sudo service nginx restart
