#!/usr/bin/env bash
# Configure the Nginx server so that to redirect to another page.

apt-get -y update && apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

redirect="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
sed -i "24i $redirect" /etc/nginx/sites-available/default

service nginx restart
