#!/usr/bin/env bash
# Bash script that creates the file /var/run/holbertonscript.pid

echo "$$" > /var/run/holbertonscript.pid

while :
do
	echo "To infinity and beyond"
        sleep2
	trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit 0' SIGTERM SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
done
