#!/usr/bin/env bash
# Displays the content of the file /etc/passwd. Only display username, user id, home directory path.

routedir="/etc/passwd"
while read route; do
	echo "$route" | cut -d ":" -f1,3,6
done < "$routedir"
