#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS.

routedir="/etc/passwd"
while IFS=: read -r USRNAME GROUP_ID HOME_DIRECTORY CSHELL USR_ID PASSWD USR_ID_INFO;
do
	echo "The user $USRNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $CSHELL. $USR_ID's place is protected by the passcode $PASSWD, more info about the user here: $USR_ID_INFO"
done < $routedir
