#!/usr/bin/env bash
# Displays bad luck for the 4th loop iteration
# Displays good luck for the 8th loop iteration
# Displays Holberton School for the other iterations

i="0"
while((i<10));
do
	if((i==3));
	then
		echo "bad luck"
	elif ((i==7)); then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
